Feature/ger 59/autenticao autorizacao
Startup-College/API-REST-catalog-lub-norte pull request #6
Opened 2024-01-13 17:58 UTC by dev-edsonlopes

2024-01-14 22:03 UTC, Maycomwill requested changes
Correção solicitada no "usersControllers".

2024-01-14 22:03 UTC, Maycomwill commented on src/controllers/usersControllers.js
```
 data: {
          name: name,
          surname: surname,
          email: email,
          password: hashedPassword,
          CPF_CNPJ: CPF_CNPJ,
          birth_date: birth_date,
        },
```
Em objetos como esse, onde os campos tem o mesmo nome que a variavel, pode-se abreviar, e utilizar apenas uma vez, ficando mais ou menos dessa forma: 

```
data: {
          name,
          surname,
          email,
          password: hashedPassword,
          CPF_CNPJ,
          birth_date,
        },
```

```
 if (!user) {
        return reply.status(400).send({ message: "Email incorreto!" });
 }

...

if (!isPasswordValid) {
        return reply.status(400).send({ message: "Senha incorreta!" });
}

```

Não é legal retornar uma mensagem informando o que tem de errado com o login, pode ajudar a quem tenta invadir alguma conta, sabendo que ta errando só a senha, ou o email também ta errado, sabe. Acho melhor informar só que "Um ou ambos dos campos está incorreto" Mesmo que seja só uma informação do server side

2024-01-15 21:29 UTC, dev-edsonlopes commented on src/controllers/usersControllers.js
### Por favor realizar novamente a validação e verificar se as correções foram atentida.

- Abreviação dos objetos
- Retorno da validação das credênciais
- Correção das inserção de dados de rotas autenticada utilizando o Prehandler

2024-01-16 23:21 UTC, Maycomwill approved these changes

2024-01-16 23:23 UTC, Maycomwill approved these changes

2024-01-16 23:23 UTC, Maycomwill approved these changes

2024-01-16 23:23 UTC, merged